# Generated by Django 5.1.2 on 2024-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
